#!/usr/bin/env python3
"""Launch multiple ssh sessions in a single iTerm2 window and broadcast keyboard input

Copyright (C) 2021-2026 David Stark

This program is free software; you can redistribute it and/or modify it under the terms of
the GNU General Public License as published by the Free Software Foundation; version 2 only.

This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with this program;
if not, write to the Free Software Foundation, Inc.,
51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
"""

import argparse
import asyncio
import logging
import os
import re
import subprocess
import sys
from dataclasses import dataclass, field
from functools import partial
from math import ceil, floor, sqrt
from subprocess import CompletedProcess
from time import monotonic, sleep
from typing import NoReturn

import iterm2
from AppKit import NSRunningApplication, NSWorkspace, NSWorkspaceOpenConfiguration
from iterm2.app import App
from iterm2.connection import Connection
from iterm2.profile import TitleComponents
from iterm2.session import Session
from iterm2.tab import Tab

logger: logging.Logger = logging.getLogger(__name__)
# We prepend U+2064 INVISIBLE PLUS to session names so we know they're from csshi
session_name_prefix = "\u2064"


@dataclass
class Config:
    broadcast: bool = True
    cols: int = 0
    debug: bool = False
    hostnames: list[str] = field(default_factory=list)
    kill_defunct: bool = False
    rows: int = 0
    shell: str = ""
    sleep: float = 0
    ssh_exec_string: str = ""
    ssh_strings: list[str] = field(default_factory=list)


def error(message: str) -> NoReturn:
    """Squeak and keel over"""
    logger.error(message)
    sys.exit(1)


def get_arg_parser() -> argparse.ArgumentParser:
    """Parse it. Parse it real good."""
    parser = argparse.ArgumentParser(
        description="Run multiple ssh connections concurrently in an iTerm2 terminal."
    )
    parser.add_argument(
        "-d", "--debug", dest="debug", action="store_true", help="Turn on debugging"
    )
    parser.add_argument(
        "-k",
        "--kill-inactive",
        dest="kill",
        action="store_true",
        help="Don't create spacer panes and kill inactive panes",
    )
    parser.add_argument(
        "-c",
        "--caffeinate",
        dest="caffeine",
        action="store_true",
        help="Try to keep the Mac awake",
    )
    parser.add_argument(
        "-n",
        "--no-broadcast",
        dest="nobroadcast",
        action="store_true",
        help="Don't enable input broadcast",
    )
    parser.add_argument(
        "-l",
        "--username",
        dest="username",
        help="Login username, overridden per-host by specifying 'user@host'",
    )
    parser.add_argument(
        "-p",
        "--port",
        dest="port",
        type=int,
        help="ssh server port, overridden per-host by specifying 'host:port'",
    )
    parser.add_argument(
        "-J",
        "--jump",
        dest="jumphost",
        help="ProxyJump host specification, like [user@]jumphost[:port]",
    )
    parser.add_argument(
        "-s",
        "--sleep",
        dest="sleep",
        default=0,
        type=float,
        help="Sleep time in seconds between hosts. Defaults to 0",
    )
    parser.add_argument(
        "-o",
        "--options",
        action="append",
        dest="options",
        help="Raw ssh options string, e.g. '-i ~/.ssh/id_ansible'. Can be specified multiple times.",
    )
    parser.add_argument(
        "-b",
        "--binary",
        dest="binary",
        default="ssh",
        help="SSH binary to use. Defaults to 'ssh'",
    )
    group = parser.add_mutually_exclusive_group()
    group.add_argument(
        "-C",
        "--columns",
        dest="columns",
        type=int,
        help="Maximum number of columns to use.",
    )
    group.add_argument(
        "-R", "--rows", dest="rows", type=int, help="Maximum number of rows to use."
    )
    parser.add_argument(
        "destinations",
        metavar="destination",
        nargs="*",
        help="[user@]host[:port] ssh server specification. NB: Square brackets MUST be used around IPv6 IP adresses",
    )
    parser.add_argument(
        "-L",
        "--list-sessions",
        dest="list_sessions",
        action="store_true",
        help="Print space-separated list of csshi sessions, one line per window",
    )
    return parser


def destination_to_hostname(destination: str) -> str:
    """Parse out a hostname from a user-specified destination spec"""
    hostname: str = ""
    if re.search(r"\[..*\]", destination):
        hostname = destination.split("[")[1].split("]")[0]
    elif "@" in destination:
        hostname = destination.split("@")[1].split(":")[0]
    elif ":" in destination:
        hostname = destination.split(":")[0]
    else:
        hostname = destination
    logger.debug(f"Found hostname {hostname} in destination {destination}")
    return hostname


def destination_to_user(destination: str) -> str | None:
    """Parse out a username from a user-specified destination spec"""
    if "@" in destination:
        user: str = destination.split("@")[0]
        logger.debug(f"Found user {user} in destination {destination}")
        return user
    else:
        return None


def destination_to_port(destination: str) -> int | None:
    """Parse out a port from a user-specified destination spec"""
    port: int | None = None
    if re.search(r"\[..*\]", destination):
        port_str: str = destination.split("]")[1].lstrip(":")
        if port_str:
            try:
                port = int(destination.split("]")[1].lstrip(":"))
            except ValueError:
                error(f"Port specified in {destination} is not an integer.")
    elif ":" in destination:
        try:
            port = int(destination.split(":")[1])
        except ValueError:
            error(f"Port specified in {destination} is not an integer.")
    if port:
        logger.debug(f"Found port {port} in destination {destination}")
        return port
    else:
        return None


def args_to_ssh_strings(args: argparse.Namespace) -> list[str]:
    """Create a list of ssh command strings from the user args."""
    ssh_strings: list[str] = []
    for destination in args.destinations:
        logger.debug(f"Setting default user {args.username or '<Not specified>'}")
        user = args.username
        logger.debug(f"Setting default port {args.port or '<Not specified>'}")
        port = args.port
        hostname: str = destination_to_hostname(destination)
        user = destination_to_user(destination) or user
        port = destination_to_port(destination) or port
        if not hostname:
            error(f"ssh host '{destination}' does not appear to include a hostname.")
        dest_ssh_args: list[str] = []
        if args.caffeine:
            dest_ssh_args.extend(["caffeinate", "-dimsu"])
        dest_ssh_args.append(args.binary)
        if user:
            logger.debug(f"User for host {hostname} is {user}")
            dest_ssh_args.extend(["-l", user])
        if port:
            logger.debug(f"Port for host {hostname} is {port}")
            dest_ssh_args.extend(["-p", str(port)])
        if args.jumphost:
            logger.debug(f"Jumphost for host {hostname} is {args.jumphost}")
            dest_ssh_args.extend(["-J", args.jumphost])
        if args.options:
            for option in args.options:
                logger.debug(f'Setting option for host {hostname}: "{option}"')
                dest_ssh_args.append(option)
        dest_ssh_args.append(hostname)
        ssh_string: str = " ".join(dest_ssh_args)
        logger.debug(f"ssh_string for host {hostname} is: {ssh_string}")
        ssh_strings.append(ssh_string)
    return ssh_strings


def get_user_shell() -> str:
    """Find the user's shell, or whichever bash is first in PATH"""
    shell: str | None = os.environ.get("SHELL")
    if shell:
        logger.debug(f"Using shell {shell} from $SHELL")
    else:
        try:
            pcomplete: CompletedProcess = subprocess.run(
                "command -v bash", shell=True, check=True, capture_output=True
            )
        except subprocess.CalledProcessError:
            error("Could not find a local shell to run. Set $SHELL or install bash.")
        shell = pcomplete.stdout.decode().strip()
        logger.debug(f"No $SHELL found, using {shell} from PATH")
    return shell


def set_columns(columns: int | None, rows: int | None, sessions: int) -> int:
    """Set a calculated number of columns, or user specified, whichever is less"""
    floor_square: int = floor(sqrt(sessions))
    if columns is not None and columns < 1:
        error("Columns cannot be < 1")
    if rows is not None and rows < 1:
        error("Rows cannot be < 1")
    if columns:
        if columns <= floor_square:
            logger.debug(f"Using columns argument: {columns}")
            return columns
        logger.debug("Not using columns argument - sqrt is lower")
    if rows:
        calc_columns = ceil(sessions / rows)
        logger.debug(
            f"Using {calc_columns} columns from {sessions} destinations, {rows} rows"
        )
        return calc_columns
    return floor_square


def build_config(args: argparse.Namespace) -> Config:
    """Build a config object from the user args"""
    config = Config()
    num_destinations: int = len(args.destinations)
    config.broadcast = not args.nobroadcast
    config.debug = args.debug
    config.hostnames = [destination_to_hostname(x) for x in args.destinations]
    config.kill_defunct = args.kill
    config.cols = set_columns(args.columns, args.rows, num_destinations)
    config.rows = ceil(num_destinations / config.cols)
    config.shell = get_user_shell()
    config.sleep = args.sleep
    config.ssh_exec_string = f"{config.shell} -c '{{ssh_string}}'"
    config.ssh_strings = args_to_ssh_strings(args)
    return config


def gen_ssh_profile() -> iterm2.LocalWriteOnlyProfile:
    """iTerm base profile for ssh panes"""
    profile = iterm2.LocalWriteOnlyProfile()
    profile.set_title_components([TitleComponents.SESSION_NAME])
    profile.set_allow_title_setting(False)
    profile.set_use_custom_command("Yes")
    profile.set_close_sessions_on_end(False)
    return profile


def gen_spacer_profile(shell: str) -> iterm2.LocalWriteOnlyProfile:
    """iTerm profile for spacer panes - Just spit out a message a wait"""
    profile = iterm2.LocalWriteOnlyProfile()
    profile.set_use_custom_command("Yes")
    profile.set_command(f'{shell} -c "/bin/echo PANE NOT IN USE"')
    profile.set_close_sessions_on_end(False)
    return profile


async def sessions_list(connection: Connection) -> None:
    """Print out sessions started by csshi"""
    logger.debug("Connecting to iTerm")
    app = await iterm2.async_get_app(connection)
    logger.debug("Connected")
    windows: dict[str, list[str]] = {}
    for window in app.windows:
        windows[window.window_id] = []
        for tab in window.tabs:
            for session in tab.sessions:
                if session.name.startswith(session_name_prefix):
                    windows[window.window_id].append(
                        session.name[len(session_name_prefix) :]
                    )
    for session_list in windows.values():
        if session_list:
            print(" ".join(session_list))


async def set_broadcast(app: App, connection: Connection, tab: Tab) -> None:
    """Attach user input to the ssh panes"""
    domain = iterm2.broadcast.BroadcastDomain()
    for session in tab.sessions:
        domain.add_session(session)
    bc_domains = app.broadcast_domains
    bc_domains.append(domain)
    logger.debug("Enabling input broadcast")
    await iterm2.async_set_broadcast_domains(connection, bc_domains)


async def monitor_sessions(app: App, con: Connection, tab: Tab, reap: bool) -> None:
    """Wait for termination messages, and close any terminated sessions"""
    async with iterm2.SessionTerminationMonitor(con) as mon:
        while tab.sessions:
            logger.debug(f"Active sessions: {tab.sessions}")
            logger.debug("Waiting for next session to close...")
            try:
                session_id = await asyncio.wait_for(mon.async_get(), timeout=2)
            except asyncio.TimeoutError:
                if not NSRunningApplication.runningApplicationsWithBundleIdentifier_(
                    "com.googlecode.iterm2"
                ):
                    logger.debug("Iterm2 is not running - ending session reaper")
                    return
                if not tab.window:
                    logger.debug("Window gone - ending session reaper")
                    return
                continue
            logger.debug(f"Got termination for {session_id}")
            if reap:
                session = app.get_session_by_id(session_id)
                if session:
                    if session in tab.sessions:
                        logger.debug(f"Closing session {session_id}")
                        await session.async_close()
                    else:
                        logger.debug(f"Ignoring session {session_id} - not in our tab")
                else:
                    logger.debug(f"Session for {session_id} gone")


def launch_handler(_, launch_error) -> None:
    """Handle iTerm2 launch callback"""
    if launch_error:
        error("Could not launch iTerm2.")


async def sessions_run(config: Config, connection: Connection) -> None:
    """Launch all sessions and spacers"""
    ssh_profile = gen_ssh_profile()
    spacer_profile = gen_spacer_profile(config.shell)
    logger.debug("Connecting to iTerm")
    app = await iterm2.async_get_app(connection)
    logger.debug("Connected")
    host_ind = 0
    # Launch the first pane straight into ssh
    logger.debug(f"Launching 1st pane, ssh_exec_string: {config.ssh_strings[host_ind]}")
    ssh_profile.set_command(
        config.ssh_exec_string.format(ssh_string=config.ssh_strings[host_ind])
    )
    ssh_profile.set_name(f"{session_name_prefix}{config.hostnames[host_ind]}")
    window = await iterm2.Window.async_create(
        connection, profile_customizations=ssh_profile
    )
    tab = window.current_tab
    # Launch the rest of the first row into ssh
    # First row will always be all ssh panes, no spacers
    column_heads: list[Session] = [tab.current_session]
    for _ in range(config.cols - 1):
        logger.debug(f"Sleeping for {config.sleep} seconds")
        await asyncio.sleep(config.sleep)
        host_ind += 1
        ssh_profile.set_command(
            config.ssh_exec_string.format(ssh_string=config.ssh_strings[host_ind])
        )
        ssh_profile.set_name(f"{session_name_prefix}{config.hostnames[host_ind]}")
        logger.debug(f"Splitting pane, ssh_exec_string: {config.ssh_strings[host_ind]}")
        column_heads.append(
            await tab.current_session.async_split_pane(
                vertical=True, profile_customizations=ssh_profile
            )
        )
    # Create the rest of the pane rows, either as ssh or spacer
    total_sessions = config.cols
    column_tails = column_heads.copy()  # new pane rows are split from the bottom
    for _ in range(config.rows - 1):
        for j in range(config.cols):
            total_sessions += 1
            if total_sessions <= len(config.ssh_strings):
                # Still launching ssh panes
                host_ind += 1
                ssh_profile.set_command(
                    config.ssh_exec_string.format(
                        ssh_string=config.ssh_strings[host_ind]
                    )
                )
                ssh_profile.set_name(
                    f"{session_name_prefix}{config.hostnames[host_ind]}"
                )
                logger.debug(f"Sleeping for {config.sleep} seconds")
                await asyncio.sleep(config.sleep)
                logger.debug(
                    f"Splitting pane, ssh_exec_string: {config.ssh_strings[host_ind]}"
                )
                last = await column_tails[j].async_split_pane(
                    vertical=False, profile_customizations=ssh_profile
                )
            elif not config.kill_defunct:
                # If '-k' flag is _not_ specified, launch spacer panes to fill last row
                logger.debug("Splitting pane for spacer")
                last = await column_tails[j].async_split_pane(
                    vertical=False, profile_customizations=spacer_profile
                )
            else:
                continue
            column_tails[j] = last
    if config.broadcast:
        await set_broadcast(app, connection, tab)
    logger.debug("Arranging panes")
    await iterm2.MainMenu.async_select_menu_item(
        connection, "Arrange Split Panes Evenly"
    )
    logger.debug("Activating 1st pane")
    await tab.sessions[0].async_activate()
    if config.kill_defunct or config.debug:
        await monitor_sessions(app, connection, tab, config.kill_defunct)


if __name__ == "__main__":
    parser = get_arg_parser()
    args = parser.parse_args()
    if args.debug:
        logging.basicConfig(level=logging.DEBUG)
    else:
        logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")
    if args.list_sessions:
        logger.debug("Entering sessions_list()")
        iterm2.run_until_complete(sessions_list)
        logger.debug("sessions_list() has completed. Exiting.")
        sys.exit(0)
    if not args.destinations:
        parser.print_usage()
        error("The following arguments are required: destination")
    config: Config = build_config(args)
    logger.debug("Launching iTerm...")
    workspace = NSWorkspace.sharedWorkspace()
    url = workspace.URLForApplicationWithBundleIdentifier_("com.googlecode.iterm2")
    if not url:
        error("Could not find iTerm2 application URL. Is iTerm2 installed?")
    nsconfig = NSWorkspaceOpenConfiguration.configuration()
    workspace.openApplicationAtURL_configuration_completionHandler_(
        url, nsconfig, launch_handler
    )
    deadline: float = monotonic() + 10
    while not NSRunningApplication.runningApplicationsWithBundleIdentifier_(
        "com.googlecode.iterm2"
    ):
        if monotonic() > deadline:
            error("Timed out waiting for iTerm2 to launch.")
        logger.debug("Waiting for iTerm2 to launch...")
        sleep(1)
    sessions_run_partial = partial(sessions_run, config)
    logger.debug("Entering sessions_run()")
    iterm2.run_until_complete(sessions_run_partial)
    logger.debug("sessions_run() has completed. Exiting.")
